modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="cooping"
version="1.0.0"
displayName="cooping"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="vitor, MCreator"

[[dependencies.cooping]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



